patterns:
  - '!.git/**'
  - '!.gitignore'
  - '!bitbucket-pipelines.yml'
  - '!node_modules/@react-native/**'
  - '!node_modules/@unimodules/react-native-adapter/android/**'
  - '!node_modules/@unimodules/react-native-adapter/ios/**'
  - '!node_modules/@unimodules/core/android/**'
  - '!node_modules/@unimodules/core/ios/**'
  - '!node_modules/react-native-securerandom/android/**'
  - '!node_modules/react-native-securerandom/ios/**'
  - '!node_modules/jsc-android/**'
  - '!node_modules/react-native/**'
  - '!node_modules/hermes-engine/**'
  - '!node_modules/aws-sdk/**'
  - '!node_modules/mocha/**'
  - '!node_modules/apollo-invalidation-policies/node_modules/typescript/**'
  - '!node_modules/pdf-lib/dist/**'
  - '!node_modules/qrcode/bin/**'
  - '!node_modules/qrcode/build/**'
  - '!node_modules/qrcode/helper/**'
  - '!node_modules/ion-js/.nyc_output/**'
  - '!node_modules/@pdf-lib/fontkit/dist/fontkit.es.js'
  - '!node_modules/@pdf-lib/fontkit/dist/fontkit.es.min.js'
  - '!node_modules/@pdf-lib/fontkit/dist/fontkit.umd.min.js'
  - '!node_modules/@pdf-lib/standard-fonts/dist/standard-fonts.min.js'
  - '!node_modules/@pdf-lib/upng/dist/UPNG.min.js'
  - '!node_modules/joi/dist/joi-browser.min.js'
  - '!node_modules/pngjs/browser.js'
  - '!node_modules/pngjs/coverage/**'
  - '!node_modules/ion-hash-js/tests/**'
  - '!node_modules/ion-hash-js/ion-hash-test/**'
  - '!node_modules/csv-stringify/dist/iife/**'
  - '!node_modules/csv-stringify/dist/umd/**'
  - '!node_modules/csv-stringify/dist/esm/**'
  - '!test/**'
  - '!**/test/**'
  - '!**/.nyc_output/**'
  - '!serverless.yml'
  - '!serverless/**'
  - '!.env*'
  - '!**/*.jar'
  - '!**/*.aar'
  - '!**/*.md'
  - '!**/*.ts'
  - '!**/*.map'
  - '!**/*.zip'
  - '!**/*.h'
  - '!**/*.coffee'
  - '!**/*.tsbuildinfo'
  - '!**/*.gradle'
  - '!**/stats.json'
  - '!**/package-lock.json'
  - '!**/.package-lock.json'
  - '!**/README.md'
  - '!**/LICENSE'
  - '!**/license'
  - '!**/LICENSE.txt'
  - '!**/LICENSE-W3C.html'
  - '!**/tsconfig.json'
  - '!**/.npmignore'
  - '!**/.editorconfig'
  - '!**/CopyrightNotice.txt'
  - '!**/tslib.html'
  - '!**/tslib.es6.html'
  - '!**/ThirdPartyNoticeText.txt'
  - '!**/jest.config.js'
  - '!**/.flowconfig'
  - '!**/.eslintrc.js'
  - '!**/tslint.json'
  - '!**/tsconfig.amd.json'
  - '!**/tsconfig.commonjs.json'
  - '!**/tsconfig.json'
  - '!**/typedoc.json'
  - '!**/.travis.yml'
  - '!**/.eslintrc.json'
  - '!**/.prettierignore'
  - '!**/.eslintignore'
  - '!**/CODEOWNERS'
  - '!**/yarn.lock'
  - '!**/NOTICE'
  - '!**/.gitmodules'
  - '!**/.zuul.yml'
  - '!**/Gruntfile.js'
  - '!**/rollup.config.js'
  - '!**/tsconfig.rollup.json'
  - '!**/tsconfig.tests.json'
  - '!**/bower.json'
  - '!**/THIRD-PARTY-LICENSES'
  - '!**/README.markdown'
  - '!**/.jshintrc'
  - '!**/.codeclimate.yml'
  - '!**/.csslintrc'
  - '!**/.snyk'
  - '!**/dist-es/**'
  - '!**/.github/**'
  - 'assets/**'
